---
- name: Create DeaDBeeF install directory
  ansible.builtin.file:
    path: /tmp/install_deadbeef
    state: directory

- name: Download DeaDBeeF
  ansible.builtin.get_url:
    url: https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.1/deadbeef-static_1.9.1-1_amd64.deb/download
    dest: /tmp/install_deadbeef/deadbeef.deb

- name: Install DeaDBeeF
  ansible.builtin.command:
    cmd: gdebi -n /tmp/install_deadbeef/deadbeef.deb
  become: true

- name: Create DeaDBeeF config directory
  ansible.builtin.file:
    path: ~/.config/deadbeef
    state: directory

- name: Copy DeaDBeeF config file
  ansible.builtin.copy:
    src: files/deadbeef_config
    dest: ~/.config/deadbeef/config

- name: Download MPRIS2 plugin source
  ansible.builtin.get_url:
    url: https://github.com/Serranya/deadbeef-mpris2-plugin/releases/download/v1.14/deadbeef-mpris2-plugin-1.14.tar.xz
    dest: /tmp/install_deadbeef/plugin.tar.xz

- name: Extract plugin source
  ansible.builtin.unarchive:
    src: /tmp/install_deadbeef/plugin.tar.xz
    dest: /tmp/install_deadbeef
    remote_src: true

- name: Install plugin build dependency
  ansible.builtin.apt:
    name: libglib2.0-dev
  become: true

- name: Copy DeaDBeeF library files to plugin install directory
  ansible.builtin.copy:
    src: /opt/deadbeef/include/deadbeef
    dest: /tmp/install_deadbeef/deadbeef-1.14
    remote_src: true

- name: Configure plugin
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: ./configure
    chdir: /tmp/install_deadbeef/deadbeef-1.14

- name: Install plugin
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: make install
    chdir: /tmp/install_deadbeef/deadbeef-1.14
  become: true

- name: Copy plugin files to DeaDBeeF library directory
  ansible.builtin.copy:
    src: /usr/local/lib/deadbeef/{{ item }}
    dest: /opt/deadbeef/lib/deadbeef/{{ item }}
    remote_src: true
  loop:
    - mpris.la
    - mpris.so
  become: true

- name: Remove plugin installation target directory
  ansible.builtin.file:
    path: /usr/local/lib/deadbeef
    state: absent
  become: true

- name: Clean up DeaDBeeF install directory
  ansible.builtin.file:
    path: /tmp/install_deadbeef
    state: absent
  become: true
