---
- name: Create git config directory
  ansible.builtin.file:
    path: ~/.config/git
    state: directory

- name: Copy git config file
  ansible.builtin.copy:
    src: git_config
    dest: ~/.config/git/config
    mode: 0664

- name: Update remote url for dotfiles repo
  ansible.builtin.command:
    cmd: git remote set-url origin git@github.com:cfgrok/dotfiles.git
    chdir: ~/Documents/workspace/dotfiles

- name: Create ssh key pair
  ansible.builtin.command:
    cmd: ssh-keygen -f ~/.ssh/id_rsa -N "" -q

- name: Add ssh key to ssh-agent
  ansible.builtin.command:
    cmd: ssh-add
