---
- name: Create git config directory
  ansible.builtin.file:
    path: ~/.config/git
    state: directory

- name: Copy git config file
  ansible.builtin.copy:
    src: git_config
    dest: ~/.config/git/config
    mode: 0664
