---
- name: Set up EULA response for MS fonts
  ansible.builtin.debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    vtype: boolean
    value: "true"
  become: true

- name: Install standard packages
  ansible.builtin.apt:
    name:
      - abcde
      - audacity
      - autojump
      - brasero
      - dconf-editor
      - exuberant-ctags
      - fd-find
      - ffmpeg
      - fonts-inconsolata
      - gimp
      - git-extras
      - gnome-gmail
      - gnome-nettool
      - htop
      - keepassxc
      - meld
      - mint-backgrounds-uma
      - nethogs
      - nfs-common
      - nmap
      - peek
      - postgresql
      - postgresql-client
      - ripgrep
      - screenkey
      - ssh-askpass-gnome
      - simplescreenrecorder
      - taskwarrior
      - tree
      - ubuntu-restricted-extras
      - vagrant
      - vim-gtk
      - virtualbox
      - vlc
    update_cache: true
  become: true
