---
- name: Download apt signing key for Neovim
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9dbb0be9366964f134855e2255f96fcf8231b6dd
    dest: /tmp/neovim-key

- name: Dearmor signing key and save in keyrings directory
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/neovim.gpg /tmp/neovim-key
    creates: /usr/share/keyrings/neovim.gpg
  become: true

- name: Remove downloaded key file
  ansible.builtin.file:
    path: /tmp/neovim-key
    state: absent

- name: Create apt source file
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/neovim.list
    content: "deb [signed-by=/usr/share/keyrings/neovim.gpg] https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu {{ ubuntu_release }} main"
    force: false
  become: true

- name: Install Neovim
  ansible.builtin.apt:
    name: neovim
    update_cache: true
  become: true

- name: Set Neovim as default application for "vi" and "vim" commands
  ansible.builtin.command:
    cmd: "update-alternatives --set {{ item }} /usr/bin/nvim"
  loop:
    - vi
    - vim
  become: true

- name: Copy Neovim config files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: ~/.config/nvim/
  loop:
    - init.vim
    - coc.vim
    - coc-settings.json
    - vim-snippets-custom.json

- name: Create plugin autoload directory
  ansible.builtin.file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Install neovim npm package
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: npm install -g neovim

- name: Install vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Install plugins and update remote plugins
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: nvim --headless +PlugInstall +UpdateRemotePlugins +qa
