---
- name: Create Neovim install directory
  ansible.builtin.file:
    path: /tmp/install_nvim
    state: directory

- name: Download Neovim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim-linux64.tar.gz"
    dest: /tmp/install_nvim/nvim-linux64.tar.gz

- name: Install Neovim
  ansible.builtin.unarchive:
    src: /tmp/install_nvim/nvim-linux64.tar.gz
    dest: /opt
  become: true

- name: Clean up Neovim install directory
  ansible.builtin.file:
    path: /tmp/install_nvim
    state: absent
  become: true

- name: Set Neovim as default application for "vi" and "vim" commands
  ansible.builtin.command:
    cmd: "update-alternatives --install /usr/bin/{{ item }} {{ item }} /opt/nvim-linux64/bin/nvim 100"
  loop:
    - vi
    - vim
  become: true

- name: Copy Neovim config files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: ~/.config/nvim/
  loop:
    - init.vim
    - coc.vim
    - coc-settings.json
    - jsonc.vim
    - vim-snippets-custom.json

- name: Create plugin autoload directory
  ansible.builtin.file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Install neovim npm package
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: source ~/.config/nvm/nvm.sh && npm install -g neovim

- name: Install vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Install plugins and update remote plugins
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: nvim --headless +PlugInstall +UpdateRemotePlugins +qa
