---
- hosts: localhost
  vars:
    bat_version: 0.21.0
    deadbeef_version: 1.9.1
    deadbeef_minor_version: 1.9.1-1
    deadbeef_plugin_version: 1.14
    dmenu2_version: 0.2.1
    home_path: "/home/{{ ansible_user_id }}"
    nerdfont_version: 2.1.0
    neovim_version: 0.9.5
    ruby_version: 3.2.2
    ubuntu_release: jammy

  tasks:

    - name: Prompt for git config email
      ansible.builtin.pause:
        prompt: Enter email for git config
        echo: true
      register: git_email_entry
      tags: git_config

    - name: Prompt for git config name
      ansible.builtin.pause:
        prompt: Enter full name for git config
        echo: true
      register: git_name_entry
      tags: git_config

    - name: Set variables for git config
      ansible.builtin.set_fact:
        git_email: "{{ git_email_entry.user_input }}"
        git_name: "{{ git_name_entry.user_input }}"
      tags: git_config


    - name: Remove unwanted default packages
      ansible.builtin.import_tasks: clean_packages.yml
      tags: clean_packages


    - name: Install standard packages
      ansible.builtin.import_tasks: install_packages.yml
      tags: install_packages


    - name: Install Alacritty
      ansible.builtin.import_tasks: alacritty.yml
      tags: alacritty


    - name: Install XMonad
      ansible.builtin.import_tasks: xmonad.yml
      tags: xmonad


    - name: Install jgmenu
      ansible.builtin.import_tasks: jgmenu.yml
      tags: jgmenu


    - name: Copy Git config
      ansible.builtin.import_tasks: git_config.yml
      tags: git_config


    - name: Create mount directories and home folder links
      ansible.builtin.import_tasks: link_dirs.yml
      tags: link_dirs


    - name: Install zsh and Oh My Zsh
      ansible.builtin.import_tasks: oh_my_zsh.yml
      tags: zsh


    - name: Install nvm and nodejs
      ansible.builtin.import_tasks: node.yml
      tags: node


    - name: Install Neovim
      ansible.builtin.import_tasks: neovim.yml
      tags: neovim


    - name: Install bat
      ansible.builtin.import_tasks: bat.yml
      tags: bat


    - name: Install rbenv and ruby
      ansible.builtin.import_tasks: rbenv.yml
      tags: rbenv


    - name: Install pCloud
      ansible.builtin.import_tasks: pcloud.yml
      tags: pcloud


    - name: Install Brave
      ansible.builtin.import_tasks: brave.yml
      tags: brave


    - name: Install DeaDBeeF
      ansible.builtin.import_tasks: deadbeef.yml
      tags: deadbeef


    - name: Install PostgreSQL
      ansible.builtin.import_tasks: postgres.yml
      tags: postgres


    - name: Update user settings
      ansible.builtin.import_tasks: settings.yml
      tags: settings


    - name: Set up taskwarrior directories and config file
      ansible.builtin.import_tasks: tasks.yml
      tags: tasks


    # Install Brother printer/scanner drivers
    - name: See if Brother driver is installed
      ansible.builtin.stat:
        path: /usr/lib/libbrscandec3.so
      register: brother_installed
      tags: brother

    - ansible.builtin.import_tasks: brother.yml
      when: not brother_installed.stat.exists or not brother_installed.stat.islnk
      tags: brother
