---
- name: Install PostgresSQL server, client and python adapter
  ansible.builtin.apt:
    name:
      - libpq-dev
      - postgresql
      - postgresql-client
      - python3-psycopg2
  become: true

- name: Set up PostgreSQL role
  community.postgresql.postgresql_user:
    name: "{{ ansible_user_id }}"
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB,REPLICATION,BYPASSRLS
  become: true
  become_user: postgres
