---
- name: Clone rbenv repository
  ansible.builtin.git:
    repo: https://github.com/rbenv/rbenv
    dest: ~/.local/rbenv

- name: Create rbenv plugins directory
  ansible.builtin.file:
    path: ~/.local/rbenv/plugins
    state: directory

- name: Clone ruby-build repository into plugins directory
  ansible.builtin.git:
    repo: https://github.com/rbenv/ruby-build
    dest: ~/.local/rbenv/plugins/ruby-build

- name: Install ruby libssl-dev dependency
  ansible.builtin.apt:
    name: libssl-dev
  become: true

- name: Define rbenv environment variable string
  ansible.builtin.set_fact:
    env_vars: export PATH=~/.local/rbenv/bin:$PATH; export RBENV_ROOT=~/.local/rbenv;

- name: Install ruby
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: "({{ env_vars }} rbenv install {{ ruby_version }})"

- name: Set global ruby version
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: "({{ env_vars }} rbenv global {{ ruby_version }})"
