---
# Set user setting with custom gsettings module from https://github.com/jistr/ansible-gsetting
- name: Set all gsettings settings
  gsetting:
    settings:
      com.linuxmint.report.ignored-reports: "['timeshift-no-setup']"
      org.blueman.plugins.powermanager.auto-power-on: "@mb false"
      org.gnome.meld.custom-font: "'Inconsolata Medium 18'"
      org.gnome.meld.use-system-font: "false"
      org.gnome.nm-applet.disable-connected-notifications: "true"
      org.gnome.nm-applet.disable-disconnected-notifications: "true"
      org.gnome.nm-applet.suppress-wireless-networks-available: "true"
      org.mate.background.picture-filename: "'/usr/share/backgrounds/linuxmint-uma/aholmes_canada.jpg'"
      org.mate.caja.desktop.computer-icon-visible: "false"
      org.mate.caja.desktop.font: "'Ubuntu 12'"
      org.mate.caja.desktop.home-icon-visible: "false"
      org.mate.caja.desktop.volumes-visible: "false"
      org.mate.interface.document-font-name: "'Sans 12'"
      org.mate.interface.gtk-shell-shows-app-menu: "true"
      org.mate.interface.gtk-theme: "'Mint-Y-Dark-Aqua'"
      org.mate.interface.font-name: "'Ubuntu 12'"
      org.mate.interface.icon-theme: "'Mint-Y-Dark-Aqua'"
      org.mate.interface.monospace-font-name: "'Inconsolata Medium 18'"
      org.mate.Marco.general.titlebar-font: "'Ubuntu Medium 12'"
      org.mate.panel.object-id-list: "['menu-bar', 'separator', 'notification-area', 'xapp-status', 'clock']"
      org.mate.peripherals-keyboard-xkb.kbd.options: "['terminate\\tterminate:ctrl_alt_bksp', 'caps\\tcaps:swapescape']"
      org.mate.peripherals-mouse.cursor-theme: "'DMZ-Black'"
      org.mate.power-manager.action-critical-battery: "'suspend'"
      org.mate.session.idle-delay: "20"
      org.mate.session.required-components-list: "['windowmanager', 'filemanager']"
      org.mate.session.required-components.panel: "''"
      org.mate.session.show-hidden-apps: "true"
      org.mate.SettingsDaemon.plugins.media-keys.logout: "'<Primary><Alt>semicolon'"
      org.mate.SettingsDaemon.plugins.media-keys.magnifier: "'disabled'"
      org.mate.SettingsDaemon.plugins.media-keys.next: "'disabled'"
      org.mate.SettingsDaemon.plugins.media-keys.on-screen-keyboard: "'disabled'"
      org.mate.SettingsDaemon.plugins.media-keys.previous: "'disabled'"
      org.mate.SettingsDaemon.plugins.media-keys.screenreader: "'disabled'"

# Use dconf module to define custom keyboard shortcuts
- name: Create custom volume mute shortcut name
  community.general.dconf:
    key: /org/mate/desktop/keybindings/custom0/name
    value: "'Volume mute'"

- name: Create custom volume mute shortcut binding
  community.general.dconf:
    key: /org/mate/desktop/keybindings/custom0/binding
    value: "'<Mod4>F4'"

- name: Create custom volume mute shortcut action
  community.general.dconf:
    key: /org/mate/desktop/keybindings/custom0/action
    value: "'pactl set-sink-mute @DEFAULT_SINK@ toggle'"

- name: Create custom volume down shortcut name
  community.general.dconf:
    key: /org/mate/desktop/keybindings/custom1/name
    value: "'Volume down'"

- name: Create custom volume down shortcut binding
  community.general.dconf:
    key: /org/mate/desktop/keybindings/custom1/binding
    value: "'<Mod4>F5'"

- name: Create custom volume down shortcut action
  community.general.dconf:
    key: /org/mate/desktop/keybindings/custom1/action
    value: "'pactl set-sink-volume @DEFAULT_SINK@ -5%'"

- name: Create custom volume up shortcut name
  community.general.dconf:
    key: /org/mate/desktop/keybindings/custom2/name
    value: "'Volume up'"

- name: Create custom volume up shortcut binding
  community.general.dconf:
    key: /org/mate/desktop/keybindings/custom2/binding
    value: "'<Mod4>F6'"

- name: Create custom volume up shortcut action
  community.general.dconf:
    key: /org/mate/desktop/keybindings/custom2/action
    value: "'pactl set-sink-volume @DEFAULT_SINK@ +5%'"

# Use dconf module to set terminal profile settings, as there is no schema to use gsettings
- name: Set background transparency shading for solarized-dark terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-dark/background-darkness
    value: "0.8"

- name: Set background to transparent for solarized-dark terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-dark/background-type
    value: "'transparent'"

- name: Disable menubar for solarized-dark terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-dark/default-show-menubar
    value: "false"

- name: Set font for solarized-dark terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-dark/font
    value: "'MesloLGS NF 16'"

- name: Disable scrollbar for solarized-dark terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-dark/scrollbar-position
    value: "'hidden'"

- name: Disable system font for solarized-dark terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-dark/use-system-font
    value: "false"

- name: Disable menubar for solarized-light terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-light/default-show-menubar
    value: "false"

- name: Set font for solarized-light terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-light/font
    value: "'MesloLGS NF 16'"

- name: Disable scrollbar for solarized-light terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-light/scrollbar-position
    value: "'hidden'"

- name: Disable system font for solarized-light terminal profile
  community.general.dconf:
    key: /org/mate/terminal/profiles/solarized-light/use-system-font
    value: "false"
