---
- name: Install dircolors-solarized
  ansible.builtin.git:
    repo: https://github.com/seebi/dircolors-solarized
    dest: ~/Documents/workspace/solarized/dircolors-solarized

- name: Copy dircolors file
  ansible.builtin.copy:
    src: ~/Documents/workspace/solarized/dircolors-solarized/dircolors.256dark
    dest: ~/.config/dircolors
    remote_src: true
