---
- name: Remove /snap/bin from PATH
  ansible.builtin.replace:
    path: /etc/environment
    regexp: ':/snap/bin'
    replace: ''
  become: true

- name: Fix mtd error on startup - copy systemd-pstore.service to /etc
  ansible.builtin.copy:
    src: /lib/systemd/system/systemd-pstore.service
    dest: /etc/systemd/system/systemd-pstore.service
    remote_src: true
  become: true

- name: Fix mtd error on startup - remove email address that triggers message
  ansible.builtin.replace:
    path: /etc/systemd/system/systemd-pstore.service
    regexp: 'modprobe@mtdpstore.service '
    replace: ''
  become: true
