---
- name: Add apt signing key for Vivaldi
  ansible.builtin.apt_key:
    url: https://repo.vivaldi.com/archive/linux_signing_key.pub
    state: present
  become: true

- name: Add Vivaldi repository
  ansible.builtin.apt_repository: 
    repo: deb https://repo.vivaldi.com/archive/deb/ stable main
    filename: vivaldi-stable
  become: true

- name: Install Vivaldi
  ansible.builtin.apt:
    name: vivaldi-stable
    update_cache: true
  become: true
