---
- name: Install cabal and xmobar dependencies
  ansible.builtin.apt:
    name:
      - cabal-install
      - libasound2-dev
      - libxpm-dev
      - xdotool
  become: true

- name: Update cabal package list
  ansible.builtin.command:
    cmd: cabal update

- name: Use cabal to build and install xmobar binary
  ansible.builtin.command:
    cmd: cabal install xmobar --flags="all_extensions"

- name: Get path for xmobar binary
  ansible.builtin.stat:
    path: ~/.cabal/bin/xmobar
  register: xmobar_path

- name: Copy xmobar binary to system directory
  ansible.builtin.copy:
    src: "{{ xmobar_path.stat.lnk_source }}"
    dest: /usr/local/bin/xmobar
    remote_src: true
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy supporting scripts to system directory
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - apt-updates
    - launch-xmobar
  become: true

- name: Create font installation directory
  ansible.builtin.file:
    path: /tmp/install_fonts
    state: directory

- name: Download Meslo LG S Nerd Font archive
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ nerdfont_version }}/Meslo.zip"
    dest: /tmp/install_fonts/Meslo.zip

- name: Extract fonts
  ansible.builtin.unarchive:
    src: /tmp/install_fonts/Meslo.zip
    dest: /tmp/install_fonts
    remote_src: true

- name: Create font directory
  ansible.builtin.file:
    path: /usr/share/fonts/truetype/Meslo LG S Nerd Font
    state: directory
  become: true

- name: Copy fonts to system directory
  ansible.builtin.copy:
    src: "/tmp/install_fonts/{{ item }}"
    dest: "/usr/share/fonts/truetype/Meslo LG S Nerd Font/{{ item }}"
  loop:
    - Meslo LG S Regular Nerd Font Complete.ttf
    - Meslo LG S Bold Nerd Font Complete.ttf
    - Meslo LG S Italic Nerd Font Complete.ttf
    - Meslo LG S Bold Italic Nerd Font Complete.ttf
  become: true

- name: Refresh font cache
  ansible.builtin.command:
    cmd: fc-cache

- name: Clean up font installation directory
  ansible.builtin.file:
    path: /tmp/install_fonts
    state: absent

- name: Get sound card configuration
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: cat /proc/asound/cards | grep '\[PCH' | awk '{print $1}'
  register: card_id

- name: Copy alsa config template
  ansible.builtin.template:
    src: files/asound.j2
    dest: /etc/asound.conf
    owner: root
    group: root
  become: true

- name: Copy xmobar config file
  ansible.builtin.copy:
    src: files/xmobarrc
    dest: ~/.config/xmobar/

- name: Uncomment xmobar line in XMonad config
  ansible.builtin.replace:
    path: ~/.config/xmonad/xmonad.hs
    regexp: '(^\s+)-- (spawn "launch-xmobar")'
    replace: '\1\2'
