- name: Install xmonad
  apt: pkg={{ item }}
  with_items:
    - libghc-xmonad-contrib-dev
    - libghc-xmonad-contrib-doc
    - libghc-xmonad-dev
    - libghc-xmonad-doc
    - suckless-tools
    - xmonad
  become: true
- name: make directory for config
  file: path="~/.xmonad" state=directory
- name: copy xmonad config
  copy: src=xmonad.hs dest=~/.xmonad/xmonad.hs
- name: reset xmonad
  shell: "xmonad --recompile"
- name: set window manager
  dconf:
    key: "/org/mate/desktop/session/required-components/windowmanager"
    value: "'xmonad'"
    state: present
