---
- name: Copy autostart files to .config/autostart directory
  ansible.builtin.copy:
    src: "/etc/xdg/autostart/{{ item }}"
    dest: ~/.config/autostart/
    remote_src: true
    mode: "0664"
    force: false

- name: Append line to disable autostart items
  ansible.builtin.lineinfile:
    path: "~/.config/autostart/{{ item }}"
    line: Hidden=true
