---
- name: Set install file path
  ansible.builtin.set_fact:
    install_file: /tmp/bat.deb

- name: Retrieve latest bat release information from GitHub API
  ansible.builtin.uri:
    url: https://api.github.com/repos/sharkdp/bat/releases/latest
    method: GET
    return_content: true
  register: api_response

- name: Find and set deb file download URL
  ansible.builtin.set_fact:
    download_url:
      "{{ api_response.json | json_query('assets[?ends_with(name, `_amd64.deb`)] \
      | [?starts_with(name, `bat_`)] | [0].browser_download_url') }}"

- name: Download bat
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ install_file }}"
    mode: "0600"

- name: Install bat
  ansible.builtin.apt:
    deb: "{{ install_file }}"
  become: true

- name: Clean up bat install file
  ansible.builtin.file:
    path: "{{ install_file }}"
    state: absent
  become: true
