---
- name: Download apt signing key for Brave and save in keyrings directory
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  become: true

- name: Create apt source file
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/brave-browser-release.list
    content: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    force: false
  become: true

- name: Install Brave
  ansible.builtin.apt:
    name: brave-browser
    update_cache: true
  become: true
