---
- name: Create DeaDBeeF install directory
  ansible.builtin.file:
    path: /tmp/install_deadbeef
    state: directory
    mode: "0700"

- name: Download DeaDBeeF
  ansible.builtin.get_url:
    url: "https://sourceforge.net/projects/deadbeef/files/travis/linux/\
      {{ deadbeef_version }}\
      /deadbeef-static_\
      {{ deadbeef_minor_version }}\
      _amd64.deb/download"
    dest: /tmp/install_deadbeef/deadbeef.deb
    mode: "0600"

- name: Install DeaDBeeF
  ansible.builtin.command:
    cmd: gdebi -n /tmp/install_deadbeef/deadbeef.deb
  become: true

- name: Create DeaDBeeF config directory
  ansible.builtin.file:
    path: ~/.config/deadbeef
    state: directory
    mode: "0775"

- name: Copy DeaDBeeF config file
  ansible.builtin.copy:
    src: files/deadbeef_config
    dest: ~/.config/deadbeef/config
    mode: "0664"

- name: Download MPRIS2 plugin source
  ansible.builtin.get_url:
    url: "https://github.com/Serranya/deadbeef-mpris2-plugin/releases/download/\
      v{{ deadbeef_plugin_version }}\
      /deadbeef-mpris2-plugin-\
      {{ deadbeef_plugin_version }}.tar.xz"
    dest: /tmp/install_deadbeef/plugin.tar.xz
    mode: "0600"

- name: Extract plugin source
  ansible.builtin.unarchive:
    src: /tmp/install_deadbeef/plugin.tar.xz
    dest: /tmp/install_deadbeef
    remote_src: true

- name: Install plugin build dependency
  ansible.builtin.apt:
    name: libglib2.0-dev
  become: true

- name: Set plugin install directory variable
  ansible.builtin.set_fact:
    plugin_install_dir: "/tmp/install_deadbeef/deadbeef-{{ deadbeef_plugin_version }}"

- name: Copy DeaDBeeF library files to plugin install directory
  ansible.builtin.copy:
    src: /opt/deadbeef/include/deadbeef
    dest: "{{ plugin_install_dir }}"
    remote_src: true
    mode: "0644"

- name: Configure plugin
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: ./configure
    chdir: "{{ plugin_install_dir }}"

- name: Install plugin
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: make install
    chdir: "{{ plugin_install_dir }}"
  become: true

- name: Copy plugin files to DeaDBeeF library directory
  ansible.builtin.copy:
    src: "/usr/local/lib/deadbeef/{{ item.name }}"
    dest: "/opt/deadbeef/lib/deadbeef/{{ item.name }}"
    remote_src: true
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { name: mpris.la, mode: "0644" }
    - { name: mpris.so, mode: "0755" }
  become: true

- name: Remove plugin installation target directory
  ansible.builtin.file:
    path: /usr/local/lib/deadbeef
    state: absent
  become: true

- name: Clean up DeaDBeeF install directory
  ansible.builtin.file:
    path: /tmp/install_deadbeef
    state: absent
  become: true
