---
- name: Create git config directory
  ansible.builtin.file:
    path: ~/.config/git
    state: directory
    mode: "0775"

- name: Copy git user file
  ansible.builtin.template:
    src: templates/git_user.j2
    dest: ~/.config/git/user
    mode: "0664"

- name: Symlink git config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/git_config"
    path: "~/.config/git/config"
    state: link

- name: Update remote url for dotfiles repo
  ansible.builtin.command:
    cmd: git remote set-url origin git@github.com:cfgrok/dotfiles.git
    chdir: ~/Documents/workspace/dotfiles

- name: Create ssh key pair
  ansible.builtin.command:
    cmd: ssh-keygen -f ~/.ssh/id_rsa -N "" -q

- name: Add ssh key to ssh-agent
  ansible.builtin.command:
    cmd: ssh-add
