---
- name: Set up EULA response for MS fonts
  ansible.builtin.debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    vtype: boolean
    value: "true"
  become: true

# TODO: possible additional packages
# apache
# build-essential
# darktable
# dunst
# fzf
# gcolor3
# gh
# kopia
# lolcat
# mkchromecast
# libsqlite-dev
# lsb-release
# jq
# obsidian
# openjdk
# pandoc
# python3-neovim
# python3-pip
# python3-venv
# sqlite
# sqlite-doc
# syncthing
# tlp
# vim-tiny
# vorta
# wezterm
# wget
# workrave
- name: Install standard packages
  ansible.builtin.apt:
    name:
      - abcde
      - audacity
      - autojump
      - dconf-editor
      - exuberant-ctags
      - fd-find
      - ffmpeg
      - fonts-inconsolata
      - gimp
      - git-extras
      - gnome-gmail
      - gnome-nettool
      - htop
      - keepassxc
      - meld
      - mint-backgrounds-uma
      - nethogs
      - nfs-common
      - nmap
      - peek
      - playerctl
      - screenkey
      - ssh-askpass-gnome
      - simplescreenrecorder
      - taskwarrior
      - tree
      - ubuntu-restricted-extras
      - vagrant
      - virtualbox
      - vlc
  become: true

- name: Set askpass path in sudo.conf
  ansible.builtin.lineinfile:
    path: /etc/sudo.conf
    line: Path askpass /usr/bin/ssh-askpass
    insertafter: "#Path askpass"
  become: true

- name: Correct autojump data_home path -- step 1
  ansible.builtin.replace:
    path: /usr/share/autojump/autojump
    regexp: ",\\n +'autojump'\\)\\)"
    replace: "))"
  become: true

- name: Correct autojump data_home path -- step 2
  ansible.builtin.replace:
    path: /usr/share/autojump/autojump
    regexp: "data_home, 'autojump.txt"
    replace: "data_home, 'autojump', 'autojump.txt"
  become: true

- name: Fix missing defaults error when launching vim-tiny
  ansible.builtin.file:
    path: /usr/share/vim/vim82/defaults.vim
    state: touch
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Symlink fd ignore file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/fdignore"
    path: ~/.fdignore
    state: link

- name: Launch Firefox to create profile directory
  ansible.builtin.shell:
    cmd: firefox & sleep 5
  changed_when: false

- name: Kill Firefox
  ansible.builtin.command:
    cmd: pkill -f firefox
  changed_when: false

- name: Find Firefox profile directory
  ansible.builtin.find:
    paths: ~/.mozilla/firefox
    file_type: directory
    patterns: "*default-release"
  register: firefox_directory

- name: Set Firefox profile directory variable
  ansible.builtin.set_fact:
    firefox_directory: "{{ firefox_directory.files[0].path }}"

- name: Download arkenfox scripts to Firefox profile directory
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/arkenfox/user.js/master/{{ item }}"
    dest: "{{ firefox_directory }}/"
    mode: "0775"
  loop:
    - prefsCleaner.sh
    - updater.sh

- name: Copy user-overrides.js to Firefox profile directory
  ansible.builtin.copy:
    src: user-overrides.js
    dest: "{{ firefox_directory }}/"
    mode: "0664"

- name: Run arkenfox update script # noqa: command-instead-of-shell
  ansible.builtin.shell:
    cmd: ./updater.sh -su
    chdir: "{{ firefox_directory }}"
  register: update_output
  changed_when: "'user.js has been backed up and replaced with the latest version!' in update_output.stdout"

- name: Copy Firefox policies file
  ansible.builtin.copy:
    src: policies.json
    dest: /usr/lib/firefox/distribution/
    owner: root
    group: root
    mode: "0644"
  become: true
