---
- name: Install jgmenu
  ansible.builtin.apt:
    name: jgmenu
  become: true

- name: Copy supporting scripts to system directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"
  loop:
    - driver-manager-pkexec
    - lightdm-settings-pkexec
    - mintsources-pkexec
  become: true

- name: Symlink jgmenu config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/jgmenurc"
    path: ~/.config/jgmenu/jgmenurc
    state: link
