---
- name: Delete the original Music folder
  ansible.builtin.file:
    path: ~/Music
    state: absent

- name: Create music mount directory
  ansible.builtin.file:
    path: /mnt/data/music
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create Music symlink
  ansible.builtin.file:
    src: /mnt/data/music
    path: ~/Music
    state: link

- name: Create documents mount directory
  ansible.builtin.file:
    path: /mnt/data/documents
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create docs symlink
  ansible.builtin.file:
    src: /mnt/data/documents
    path: ~/docs
    state: link

- name: Create photos mount directory
  ansible.builtin.file:
    path: /mnt/data/photos
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create archive mount directory
  ansible.builtin.file:
    path: /mnt/data/archive
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create backup mount directory
  ansible.builtin.file:
    path: /mnt/data/backup
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create pCloud sync directory
  ansible.builtin.file:
    path: ~/Sync
    state: directory
    mode: "0775"
