---
- name: Install nvm
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm
    dest: ~/.config/nvm

- name: Install node
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: source ~/.config/nvm/nvm.sh && nvm install --lts
