---
- name: Create install dir
  ansible.builtin.file:
    path: /opt/pcloud
    state: directory
  become: true

- name: Get JSON from API
  ansible.builtin.uri:
    url: https://api.pcloud.com/getpublinkdownload?code=XZAwMrVZidapyDxpd2pCNlGy3BcjdbYCf1Yk
    method: GET
    return_content: true
  register: json_response

- name: Set download URL
  ansible.builtin.set_fact:
    download_url: "https://{{ json_response.json.hosts[0] }}{{ json_response.json.path }}"

- name: Download pCloud
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: /opt/pcloud/pcloud
    mode: a+x
  become: true

- name: Add autostart file for pCloud
  ansible.builtin.copy:
    src: pcloud.desktop
    dest: ~/.config/autostart/
    mode: "0644"
