---
- name: Clone rbenv repository
  ansible.builtin.git:
    repo: https://github.com/rbenv/rbenv
    dest: ~/.local/rbenv

- name: Create rbenv plugins directory
  ansible.builtin.file:
    path: ~/.local/rbenv/plugins
    state: directory

- name: Clone ruby-build repository into plugins directory
  ansible.builtin.git:
    repo: https://github.com/rbenv/ruby-build
    dest: ~/.local/rbenv/plugins/ruby-build

- name: Install ruby dependencies
  ansible.builtin.apt:
    name:
      - autoconf
      - build-essential
      - libdb-dev
      - libffi-dev
      - libgdbm-dev
      - libgmp-dev
      - libncurses5-dev
      - libreadline-dev
      - libssl-dev
      - libyaml-dev
      - rustc
      - uuid-dev
      - zlib1g-dev
  become: true

- name: Define rbenv environment variable string
  ansible.builtin.set_fact:
    env_vars: export PATH=~/.local/rbenv/bin:$PATH; export RBENV_ROOT=~/.local/rbenv;

- name: Install ruby
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: "({{ env_vars }} rbenv install -s {{ ruby_version }})"

- name: Set global ruby version
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: "({{ env_vars }} rbenv global {{ ruby_version }})"

- name: Define rbenv initialization variable string
  ansible.builtin.set_fact:
    rbenv_init: eval "$( rbenv init - zsh )";

- name: Install solargraph gem
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: "({{ env_vars }} {{ rbenv_init }} gem install solargraph)"

- name: Clone reline repository
  ansible.builtin.git:
    repo: https://github.com/ruby/reline
    dest: ~/Documents/workspace/reline

- name: Build reline gem
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: rake build
    chdir: ~/Documents/workspace/reline

- name: Install reline gem
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: "({{ env_vars }} {{ rbenv_init }} gem install ~/Documents/workspace/reline/pkg/*.gem)"

- name: Symlink irbrc file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/irbrc"
    path: ~/.irbrc
    state: link
