---
- name: Create taskwarrior config directory
  ansible.builtin.file:
    path: ~/.config/task/hooks
    state: directory
    mode: "0775"

- name: Symlink taskwarrior config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/taskrc"
    path: ~/.config/task/taskrc
    state: link

- name: Create taskwarrior data directory
  ansible.builtin.file:
    path: ~/.local/share/task
    state: directory
    mode: "0775"
