---
#partner repo
- name: partner repository
  apt_repository: repo='deb http://archive.canonical.com/ubuntu xenial partner'
  become: true
- name: partner repository (src)
  apt_repository: repo='deb-src http://archive.canonical.com/ubuntu xenial partner'
  become: true

# remove ibus ctrl+space binding
- name: fix ibus keybinding
  command: gsettings set org.freedesktop.ibus.general.hotkey triggers '[]'
