---
- name: Remove unwanted default packages
  apt:
    name:
      - thunderbird
      - transmission-common
      - transmission-gtk
      - vim-tiny
    state: absent
    purge: yes
  become: true
