---
- name: create install dir
  file: path=/tmp/install_dbvis state=directory
- name: download dbvis
  get_url: dest="/tmp/install_dbvis/dbvis.deb" url=https://www.dbvis.com/product_download/dbvis-10.0.6/media/dbvis_linux_10_0_6.deb
- name: make sure we have gdebi
  apt: pkg=gdebi-core
  become: true
- name: install dbvis
  command: gdebi -n /tmp/install_dbvis/dbvis.deb
  become: true
- name: clean up
  file: path=/tmp/install_dbvis state=absent
