---
- name: Create deadbeef install directory
  file:
    path: /tmp/install_deadbeef
    state: directory

- name: Download deadbeef
  get_url:
    url: https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.1/deadbeef-static_1.9.1-1_amd64.deb/download
    dest: /tmp/install_deadbeef/deadbeef.deb

- name: Install deadbeef
  command: gdebi -n /tmp/install_deadbeef/deadbeef.deb
  become: true

- name: Clean up deadbeef install directory
  file:
    path: /tmp/install_deadbeef
    state: absent
