---
- name: add the Oracle Java JDK repository
  apt_repository: repo=ppa:webupd8team/java
  become: true
- name: set Java acceptance
  shell: sudo echo oracle-java9-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  become: true
- name: install Java
  apt: pkg=oracle-java9-installer
  become: true
