#clean out some stuff
- import_tasks: clean_packages.yml

#standard packages
- import_tasks: std_packages.yml

#git config
- import_tasks: gitconfig.yml

#pCloud
- name: See if pCloud is installed
  stat: path=/opt/pcloud/pcloud
  register: pcloud_installed
- import_tasks: pcloud.yml
  when: (not pcloud_installed.stat.exists or not pcloud_installed.stat.executable)

#vivaldi
- name: See if vivaldi is installed
  stat: path=/usr/bin/vivaldi
  register: vivaldi_installed
- import_tasks: vivaldi.yml
  when: (not vivaldi_installed.stat.exists or not vivaldi_installed.stat.executable)

# Google Chrome
- name: See if chrome is installed
  stat:
    path: /opt/google/chrome/chrome
  register: chrome_installed
- import_tasks: google_chrome.yml
  when: (not chrome_installed.stat.exists or not chrome_installed.stat.executable)

# Deadbeef
- name: See if deadbeef is installed
  stat:
    path: /opt/deadbeef/bin/deadbeef
  register: deadbeef_installed
- import_tasks: deadbeef.yml
  when: (not deadbeef_installed.stat.exists or not deadbeef_installed.stat.executable)

#zsh
- name: See if Oh My Zsh is installed
  stat:
    path: ~/.config/oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  register: oh_my_zsh_installed
- import_tasks: oh_my_zsh.yml
  when: not oh_my_zsh_installed.stat.exists

- import_tasks: symlink_dirs.yml

#solarized
- name: See if solarized is installed
  stat: path=~/.config/dircolors
  register: solarized_installed
- import_tasks: solarize.yml
  when: not solarized_installed.stat.exists

#rbenv
- name: See if rbenv is installed
  stat:
    path: ~/.local/rbenv
  register: rbenv_installed
- import_tasks: rbenv.yml
  when: not rbenv_installed.stat.exists

#vim
- import_tasks: vim.yml

# Install nvm and nodejs
- import_tasks: node.yml
  tags: node

# PostgreSQL role
- import_tasks: postgres.yml

# Update user settings
- import_tasks: settings.yml
