#clean out some stuff
- include: clean_packages.yml
  sudo: yes

#standard packages
- include: std_packages.yml
  sudo: true

#git config
- include: gitconfig.yml

- include: file_descriptors.yml

#dropbox
- name: See if dropbox is installed
  command: find /usr/bin/ -name 'dropbox'
  register: dropbox_installed
- include: dropbox.yml
  when: (not dropbox_installed.stdout)

#chrome
- name: See if chrome is installed
  command: find /usr/bin -name 'google-chrome'
  register: chrome_installed
- include: google_chrome.yml
  when: (not chrome_installed.stdout)

- include: oh_my_zsh.yml
- include: tmux.yml
- include: scripts.yml

- include: install_java.yml
- include: window_applet.yml

- include: solarize.yml
- include: compass_icons.yml
- include: gdrive.yml
