#standard packages
- include: std_packages.yml

#git config
- include: gitconfig.yml

- include: file_descriptors.yml

#pCloud
- name: See if pCloud is installed
  command: find /usr/bin/ -name 'psyncgui'
  register: pcloud_installed
- include: pcloud.yml
  when: (not pcloud_installed.stdout)

#vivaldi
- name: See if vivaldi is installed
  command: find /usr/bin -name 'vivaldi'
  register: vivaldi_installed
- include: vivaldi.yml
  when: (not vivaldi_installed.stdout)

- include: oh_my_zsh.yml
- include: tmux.yml
- include: symlink_dirs.yml

- include: install_java.yml

#dbvis
- name: See if dbvis is installed
  command: find /usr/bin -name 'dbvis'
  register: dbvis_installed
- include: dbvis.yml
  when: (not dbvis_installed.stdout)

- include: solarize.yml
- include: tlp.yml
