#standard packages
- include: std_packages.yml

#git config
- include: gitconfig.yml

- include: file_descriptors.yml

#pCloud
- name: See if pCloud is installed
  command: find /usr/bin/ -name 'psyncgui'
  register: pcloud_installed
- include: pcloud.yml
  when: (not pcloud_installed.stdout)

#chrome
- name: See if chrome is installed
  command: find /usr/bin -name 'google-chrome'
  register: chrome_installed
- include: google_chrome.yml
  when: (not chrome_installed.stdout)

- include: oh_my_zsh.yml
- include: tmux.yml
- include: symlink_dirs.yml

#- include: install_java.yml

- include: solarize.yml
- include: tlp.yml
