---
# https://gist.github.com/tsabat/1498393
- name: See if zsh is installed
  stat: path=~/.oh-my-zsh
  register: zsh_installed
- name: zsh
  apt: pkg=zsh
  become: true
- name: relax chsh restrictions
  lineinfile:
    path: /etc/pam.d/chsh
    regexp: 'auth.+pam_shells.so'
    line: 'auth       sufficient   pam_shells.so'
  become: yes
- name: install oh my zsh
  shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
  when: not zsh_installed.stat.exists
- name: restore chsh restrictions
  lineinfile:
    path: /etc/pam.d/chsh
    regexp: 'auth.+pam_shells.so'
    line: 'auth       required   pam_shells.so'
  become: yes
- name: zshrc config
  copy: src=zshrc dest=~/.zshrc
- name: git-patch plugin
  copy: src=git-patch.plugin.zsh dest=~/.oh-my-zsh/custom/plugins/git-patch/
- name: "install custom plugin: zsh-autosuggestions"
  git: repo=git://github.com/zsh-users/zsh-autosuggestions dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
- name: "install custom plugin: zsh-syntax-highlighting"
  git: repo=git://github.com/zsh-users/zsh-syntax-highlighting dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
