---
- name: Install python PostgresSQL adapter
  apt:
    name: python3-psycopg2
  become: true

- name: Check for PostgreSQL role
  postgresql_info:
    filter: roles
  become: true
  become_user: postgres
  register: role_check

- name: Set up PostgreSQL role
  postgresql_user:
    name: "{{ ansible_user_id }}"
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB,REPLICATION,BYPASSRLS
  become: true
  become_user: postgres
  when: ansible_user_id not in role_check.roles
