---
- name: Set up EULA response for MS fonts
  debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    vtype: boolean
    value: true
  become: true

- name: Install core standard packages
  apt:
    name:
      - abcde
      - audacity
      - autojump
      - brasero
      - dconf-editor
      - exuberant-ctags
      - fd-find
      - ffmpeg
      - fonts-inconsolata
      - gimp
      - git-extras
      - gnome-nettool
      - htop
      - kazam
      - keepassx
      - meld
      - nethogs
      - nfs-common
      - nmap
      - phantomjs
      - postgresql
      - postgresql-client
      - ripgrep
      - taskwarrior
      - tree
      - ubuntu-restricted-extras
      - vagrant
      - vim-gtk
      - virtualbox
      - vlc
    update_cache: true
  become: true
