---
#Music
- name: stat Music dir
  stat: path=~/Music
  register: st
- debug: msg="Music folder Exists; {{ st.stat.exists }} | isDir; {{ st.stat.isdir }}"
- name: Delete the original Music folder
  file: state=absent path="~/Music"
  when: st.stat.exists and st.stat.isdir
- name: Music symlink
  file: state=link path="~/Music" src="/mnt/data/Music"

- name: scripts symlink
  file: state=link path="~/scripts" src="~/pCloud Sync/scripts"
