---
#Music
- name: stat original Music dir
  stat: path=~/Music
  register: st
- name: delete the original Music folder
  file: state=absent path="~/Music"
  when: st.stat.exists and st.stat.isdir
- name: stat mount Music dir
  stat: path=/mnt/data/Music
  register: st
- name: create mount dir if not present
  file: state=directory path="/mnt/data/Music"
  become: true
- name: Music symlink
  file: state=link path="~/Music" src="/mnt/data/Music"
- name: scripts symlink
  file: state=link path="~/scripts" src="~/pCloud Sync/scripts" force=yes
