---
- name: See if vimrc is already present
  stat:
    path: ~/.config/vim/vimrc
  register: vimrc_exists

- name: Copy vimrc config file
  copy:
    src: vimrc
    dest: ~/.config/vim/vimrc
  when: not vimrc_exists.stat.exists

- name: Create undo directory
  file:
    path: ~/.config/vim/undo
    state: directory

- name: Copy Emmet snippet file
  copy:
    src: vim_snippets_custom.json
    dest: ~/.config/vim/vim_snippets_custom.json
