---
- name: add apt signing key for vivaldi
  apt_key:
    url: https://repo.vivaldi.com/archive/linux_signing_key.pub
    state: present
  become: true
- name: add vivaldi repository
  apt_repository: 
    repo: deb https://repo.vivaldi.com/archive/deb/ stable main
    filename: vivaldi-stable
  become: true
- name: install vivaldi
  apt:
    name: vivaldi-stable
    update_cache: yes
  become: true
