import = ["/home/ezra/.config/alacritty/alacritty_solarized_dark.toml"]
# import = ["/home/ezra/.config/alacritty/solarized-osaka.toml"]

[font]
size = 17.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[window]
opacity = 0.8

[keyboard]
bindings = [
  { key = "Home", mods = "Alt", chars = "\u001bOH" },
  { key = "End", mods = "Alt", chars = "\u001bOF" },
  # { key = "A", mods = "Alt", chars = "\u001bOH" },
  # { key = "E", mods = "Alt", chars = "\u001bOF" },
  { key = "Enter", mods = "Shift", chars = "\u001b[13;2u" },
  { key = "Space", mods = "Shift", chars = "\u001b[32;2u" },
  { key = ")", mods = "Alt|Shift", chars = "\u001b[41;3u" },
]
