import = ["/home/ezra/.config/alacritty/alacritty_solarized_dark.toml"]

[font]
size = 17.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[window]
opacity = 0.75

[keyboard]
bindings = [
  { key = "A", mods = "Alt", chars = "\u001bOH" },
  { key = "Home", mods = "Alt", chars = "\u001bOH" },
  { key = "E", mods = "Alt", chars = "\u001bOF" },
  { key = "End", mods = "Alt", chars = "\u001bOF" },
]
