export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
[[ $TERM != "linux" ]] && [[ -r $XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh ]] && source $XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh

# Add local bin directory to path for scripting if not present
[[ ! $PATH =~ $HOME/.local/bin ]] && export PATH=$HOME/.local/bin:$PATH

# Path to your oh-my-zsh configuration.
ZSH=$XDG_CONFIG_HOME/oh-my-zsh

# Disable PowerLevel10K theme & functionality in console
[ $TERM != "linux" ] && ZSH_THEME=powerlevel10k/powerlevel10k

# History settings
HIST_IGNORE_SPACE=true
HIST_STAMPS="yyyy-mm-dd"
HISTFILE=$XDG_CONFIG_HOME/zsh/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

# Set autocomplete to bypass leading dots
setopt globdots

# Set autosuggest highlight style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=10

# Remove right indent for improved display of powerlevel10k theme
ZLE_RPROMPT_INDENT=0

# Prevent expansion for listed aliases
GLOBALIAS_FILTER_VALUES=(grep l la)

# Set preferred text editor
export EDITOR="nvim"
export VISUAL="nvim"

plugins=(
  aliases
  autojump
  bundler
  colored-man-pages
  colorize
  common-aliases
  copyfile
  copypath
  dirhistory
  fd
  git
  git-extras
  globalias
  jsontools
  nmap
  nvm
  rails
  rake
  rake-fast
  ripgrep
  rsync
  sudo
  taskwarrior
  ubuntu
  ufw
  vagrant
  web-search
  zsh-autosuggestions
  zsh-interactive-cd
  zsh-syntax-highlighting
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Reset "Alt-l" keybinding to downcase word rather than execute ls command
bindkey '\el' down-case-word

# Set up "fd" alias for fd-find
alias fd=fdfind

# Remove confirmation aliases for cp, mv & rm from common-aliases plugin
unalias cp
unalias mv
unalias rm

# Replace "gdt" alias from git plugin
alias gdt="git difftool --dir-diff"
alias gdtr="git diff-tree --no-commit-id --name-only -r"

# Disable completion for implicit dot and double dot directories
zstyle ':completion:*' special-dirs false

# Solarized colors for ls commands
[[ -f $XDG_CONFIG_HOME/dircolors ]] && eval $( dircolors $XDG_CONFIG_HOME/dircolors )

# Use solarized theme for bat
export BAT_THEME="Solarized (dark)"
export FZF_PREVIEW_PREVIEW_BAT_THEME="Solarized (dark)"

# Set config path for rg command
export RIPGREP_CONFIG_PATH=$XDG_CONFIG_HOME/rg/rgrc

# Powerlevel10K -- to customize prompt, run `p10k configure` or edit $ZSH/custom/powerlevel10k/p10k.zsh
[[ -f $ZSH/custom/powerlevel10k/p10k.zsh ]] && [[ $TERM != "linux" ]] && source $ZSH/custom/powerlevel10k/p10k.zsh

# Initialize fzf if present
[[ -f $XDG_CONFIG_HOME/fzf/fzf.zsh ]] && source $XDG_CONFIG_HOME/fzf/fzf.zsh

# Alias for editing init.vim config
alias vimrc="${=EDITOR} $XDG_CONFIG_HOME/nvim/init.vim"

# Add rbenv to PATH & initialize
export PATH=$HOME/.local/rbenv/bin:$PATH
export RBENV_ROOT=$HOME/.local/rbenv
[[ -f $HOME/.local/rbenv/bin/rbenv ]] && eval "$( rbenv init - zsh )"

# Add nvim to PATH
export PATH=/opt/nvim-linux64/bin:$PATH

# Custom function to swap names of 2 files
function swap { mv $1 $1.tmp && mv $2 $1 && mv $1.tmp $2 }

#Custom function to pipe stdout & stderr both to the screen and a log file
function cmdlog { ( echo ${@:2} && ${@:2} ) |& tee -a $1 ;}
