# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [ "$TERM" != "linux" ] && [ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh configuration.
ZSH="${XDG_CONFIG_HOME:-$HOME/.config}"/oh-my-zsh

# Disable PowerLevel10K theme & functionality in console
[ "$TERM" != "linux" ] && ZSH_THEME=powerlevel10k/powerlevel10k

# History settings
HIST_IGNORE_SPACE="true"
HIST_STAMPS="yyyy-mm-dd"
HISTFILE="${XDG_CONFIG_HOME:-$HOME/.config}"/zsh/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

# Set autocomplete to bypass leading dots
setopt globdots

# Set autosuggest highlight style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=10

# Remove right indent for improved display of powerlevel10k theme
ZLE_RPROMPT_INDENT=0

# Prevent expansion for listed aliases
GLOBALIAS_FILTER_VALUES=(grep l la)

# Set preferred text editor
export EDITOR="vim"
export VISUAL="vim"

plugins=(
  aliases
  autojump
  bundler
  colored-man-pages
  colorize
  common-aliases
  copyfile
  copypath
  dirhistory
  fd
  git
  git-extras
  globalias
  jsontools
  nmap
  rails
  rake
  rake-fast
  ripgrep
  rsync
  sudo
  taskwarrior
  ubuntu
  ufw
  vagrant
  web-search
  zsh-autosuggestions
  zsh-interactive-cd
  zsh-syntax-highlighting
)

# Load Oh My Zsh
source "$ZSH"/oh-my-zsh.sh

# Set up "fd" alias for fd-find
alias fd=fdfind

# Alias for editing .vimrc config
alias vimrc="${=EDITOR} $HOME"/.vimrc

# Work around "acs" alias/command conflict between alias (cheat sheet) and ubuntu plugins
unalias acs
alias acse="apt-cache search"

# Remove confirmation aliases for cp, mv & rm from common-aliases plugin
unalias cp
unalias mv
unalias rm

# Replace "gdt" alias from git plugin
alias gdt="git difftool --dir-diff"
alias gdtr="git diff-tree --no-commit-id --name-only -r"

# Disable completion for implicit dot and double dot directories
zstyle ':completion:*' special-dirs false

# Solarized colors for ls commands
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/dircolors ]; then
  eval $(dircolors "${XDG_CONFIG_HOME:-$HOME/.config}"/dircolors)
fi

# Powerlevel10K -- to customize prompt, run `p10k configure` or edit "$ZSH"/custom/powerlevel10k/p10k.zsh
[ -f "$ZSH"/custom/powerlevel10k/p10k.zsh ] && [ "$TERM" != "linux" ] && source "$ZSH"/custom/powerlevel10k/p10k.zsh

# Initialize fzf if present
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh ] && source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh

# Add rbenv to PATH & initialize
export PATH="$HOME/.local/rbenv/bin:$HOME/.local/bin:$PATH"
export RBENV_ROOT="$HOME"/.local/rbenv
eval "$(rbenv init -)"

# Custom function to swap names of 2 files
function swap() { mv "$1" "$1".tmp && mv "$2" "$1" && mv "$1".tmp "$2" }

#Custom function to pipe stdout & stderr both to the screen and a log file
function cmdlog() { ( echo "${@:2}" && "${@:2}" ) |& tee -a "$1" ;}
