---
- name: Primary machine install
  hosts: localhost
  vars:
    ubuntu_release: jammy

  tasks:
    # TODO: install redis from ppa

    - name: Prompt for git config email
      ansible.builtin.pause:
        prompt: Enter email for git config
        echo: true
      register: git_email_entry
      tags: git_config

    - name: Prompt for git config name
      ansible.builtin.pause:
        prompt: Enter full name for git config
        echo: true
      register: git_name_entry
      tags: git_config

    - name: Set variables for git config
      ansible.builtin.set_fact:
        git_email: "{{ git_email_entry.user_input }}"
        git_name: "{{ git_name_entry.user_input }}"
      tags: git_config

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true
      tags:
        - install_packages
        - xmonad
        - jgmenu
        - zsh
        - rbenv
        - deadbeef
        - postgres
        - brother

    - name: Remove unwanted default packages
      ansible.builtin.import_tasks: tasks/clean_packages.yml
      tags: clean_packages

    - name: Install standard packages
      ansible.builtin.import_tasks: tasks/install_packages.yml
      tags: install_packages

    - name: Install Alacritty
      ansible.builtin.import_tasks: tasks/alacritty.yml
      tags: alacritty

    - name: Install XMonad
      ansible.builtin.import_tasks: tasks/xmonad.yml
      tags: xmonad

    - name: Install jgmenu
      ansible.builtin.import_tasks: tasks/jgmenu.yml
      tags: jgmenu

    - name: Copy Git config
      ansible.builtin.import_tasks: tasks/git_config.yml
      tags: git_config

    - name: Install Lazygit
      ansible.builtin.import_tasks: tasks/lazygit.yml
      tags: lazygit

    - name: Create mount directories and home folder links
      ansible.builtin.import_tasks: tasks/link_dirs.yml
      tags: link_dirs

    - name: Install zsh and Oh My Zsh
      ansible.builtin.import_tasks: tasks/oh_my_zsh.yml
      tags: zsh

    - name: Set nodejs version
      ansible.builtin.import_tasks: tasks/node_version.yml
      tags: [neovim, node]

    - name: Install nvm and nodejs
      ansible.builtin.import_tasks: tasks/node.yml
      tags: node

    - name: Install Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
      tags: neovim

    - name: Install bat
      ansible.builtin.import_tasks: tasks/bat.yml
      tags: bat

    - name: Install rbenv and ruby
      ansible.builtin.import_tasks: tasks/rbenv.yml
      tags: rbenv

    - name: Install pCloud
      ansible.builtin.import_tasks: tasks/pcloud.yml
      tags: pcloud

    - name: Install Brave
      ansible.builtin.import_tasks: tasks/brave.yml
      tags: brave

    - name: Install DeaDBeeF
      ansible.builtin.import_tasks: tasks/deadbeef.yml
      tags: deadbeef

    - name: Install PostgreSQL
      ansible.builtin.import_tasks: tasks/postgres.yml
      tags: postgres

    - name: Update user settings
      ansible.builtin.import_tasks: tasks/settings.yml
      tags: settings

    - name: Set up taskwarrior directories and config file
      ansible.builtin.import_tasks: tasks/tasks.yml
      tags: tasks

    - name: Install Brother printer/scanner drivers
      ansible.builtin.import_tasks: tasks/brother.yml
      tags: brother

    - name: Include debugging
      ansible.builtin.include_tasks: tasks/debug.yml
      tags: debug
